import Head from 'next/head';
import { NavBar } from '../components/NavBar';


export default function Formula1() {
  return (
    <>
      <Head>
        <title>Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <NavBar/>
        <section className='px-5'>
          <div className='bg-primary my-5 mx-auto w-2/3 h-60 '>
            <h1 className=' text-textgray'>ad</h1>
          </div>
          <div className='flex'>
            <div className='flex-1 mr-2 border-primary border-t-8 border-r-8 rounded-tr-3xl'>
              <h3 className='text-primary text-xxs font-bold mt-5'>FEATURE</h3>
              <h1 className='text-3xl pt-1 pb-3'>Lawrence Barretto’s 5 bold predictions for the 2023 season – how many of these will come true?</h1>
              <div className='h-80 w-1/1 mx-auto ' >
                <img src="" alt="0258823938" />
              </div>
            </div>
            <div className='flex-1 flex ml-2 max-h-96 flex-col lg:flex-row lg:flex-wrap box-border '>
              <div className='w-32 bg-black  h-32'></div>
              <div className='w-32 bg-red-500  h-32'></div>
              <div className='w-32 bg-black  h-32'></div>
              <div className='w-32  bg-black h-32'></div>
              <div className='w-32 bg-black  h-32'></div>
              <div className='w-32 bg-black  h-32'></div>
              <div className='w-32 bg-black  h-32'></div>
              <div className='w-32  bg-black h-32'></div>
              <div className='w-32 bg-black  h-32'></div>
              <div className='w-32 bg-black  h-32'></div>
              <div className='w-32 bg-black  h-32'></div>
              <div className='w-32 bg-black  h-32'></div>
              <div className='w-32 bg-black  h-32'></div>
              <div className='w-32 bg-black  h-32'></div>
              <div className='w-32 bg-black  h-32'></div>
              <div className='w-32 bg-black  h-32'></div>
              <div className='w-32 bg-black  h-32'></div>
              <div className='w-32 bg-black  h-32'></div>
              <div className='w-32 bg-black  h-32'></div>
              <div className='w-32 bg-black  h-32'></div>
            </div>
          </div>
        </section>
      </main>
    </>
  )
}
