import Head from 'next/head';
import { NavBar } from '../components/NavBar';
import { NewsCard } from '../components/NewsCard';
import { RedButton } from '../components/RedButton';
import Image from 'next/image';
import img from '../public/f1grid.jpg';
import ad from '../public/ad1.jpg';


export default function Formula1() {
  return (
    <>
      <Head>
        <title>Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='tracking-wider font-titilliumWebRegular'>
        <NavBar/>
        <section className='px-5 md:p-20 lg:p-5 '>
          <div className='bg-textgray my-5 mx-auto w-2/3 '>
            <Image src={ad} alt='ad' width={'100%'} height={'100%'} />
          </div>
          <div className='flex flex-row gap-4 pb-10 box-border overflow-hidden flex-wrap lg:flex-nowrap '>
            <div className=' pr-4 font-titilliumWebBold border-primary group border-t-8 border-r-8 rounded-tr-3xl lg:flex-1'>
              <h3 className='text-primary text-xxs mt-5'>FEATURE</h3>
              <div className='my-auto'>
                <h1 className='text-4xl pt-1 pb-4 group-hover:underline '>Lawrence Barretto’s 5 bold predictions for the 2023 season – how many of these will come true?</h1>
                <div className=' w-1/1 mx-auto ' >
                    <Image className=' object-contain ' src={img} alt='9080' width={'100%'} height={'100%'}/>
                </div>
              </div>
            </div>
            <div className=' h-[31rem] lg:flex-1'>
              <div className='flex h-full flex-row flex-wrap gap-5 overflow-scroll scrollbar-hide'>
                <NewsCard
                    className1='bg-white '
                    type='NEWS'
                    text='WATCH: Extended highlights of your favourite race of last year – the 2022 British Grand Prix'
                    image={img}
                    />
                <NewsCard
                    className1='bg-white '
                    type='VIDEO'
                    text='WATCH: Extended highlights of your favourite race of last year – the 2022 British Grand Prix'
                    image={img}
                    />
                <NewsCard
                    className1='bg-white '
                    type='NEWS'
                    text='WATCH: Extended highlights of your favourite race of last year – the 2022 British Grand Prix'
                    image={img}
                    />
                <NewsCard
                    className1='bg-white '
                    type='NEWS'
                    text='WATCH: Extended highlights of your favourite race of last year – the 2022 British Grand Prix'
                    image={img}
                    />
                <NewsCard
                    className1='bg-white '
                    type='NEWS'
                    text='WATCH: Extended highlights of your favourite race of last year – the 2022 British Grand Prix'
                    image={img}
                    />
                <NewsCard
                    className1='bg-white '
                    type='VIDEO'
                    text='WATCH: Extended highlights of your favourite race of last year – the 2022 British Grand Prix'
                    image={img}
                    />  
              </div>
              <RedButton
                className='bg-primary'
                value='VIEW LATEST NEWS >'
                />
            </div>
          </div>
          <div className='flex-1 my-10 border-primary border-y-8 border-r-8 rounded-tr-3xl rounded-br-3xl'>
            <h2 className='text-3xl -mt-6 pr-4 font-bold bg-white w-fit'>Editor's Picks</h2>
            <div className='flex flex-col flex-wrap gap-4 overflow-hidden pr-4 py-6 lg:flex-row'>
                <div className='flex-1 '>
                  <div className=' w-full max-w-[625px] max-h-[352px] mx-auto ' >
                    <Image className=' object-contain' src={img} alt='9080' width={'100%'} height={'100%'} />
                  </div>
                </div>
                <div className='flex-1  '>
                  <div className='flex h-full flex-row flex-wrap gap-5'>
                    <NewsCard
                        className1='bg-white '
                        type='FEATURE'
                        text='WATCH: Extended highlights of your favourite race of last year – the 2022 British Grand Prix'
                        image={img}
                        />
                    <NewsCard
                        className1='bg-white '
                        type='FEATURE'
                        text='WATCH: Extended highlights of your favourite race of last year – the 2022 British Grand Prix'
                        image={img}
                        />
                    <NewsCard
                        className1='bg-white '
                        type='FEATURE'
                        text='WATCH: Extended highlights of your favourite race of last year – the 2022 British Grand Prix'
                        />
                    <NewsCard
                        className1='bg-white '
                        type='FEATURE'
                        text='WATCH: Extended highlights of your favourite race of last year – the 2022 British Grand Prix'
                        />
                  </div>
                </div>
            </div>
          </div>

          <h1 className='text-2xl font-bold' >More News</h1>
          <div className='w-full border-t-8 border-black pt-4'>
            <div className='flex flex-row flex-wrap pb-4 lg:p-0 lg:flex-nowrap py-5 gap-5'>
            <NewsCard
                className1='border-none group-hover:bg-button2 rounded-br-xl rounded-bl-xl  '
                className2='group-hover:bg-red rounded-br-xl rounded-bl-xl hover:text-white'
                type='NEWS'
                text='WATCH: Extended highlights of your favourite race of last year – the 2022 British Grand Prix'
                image={img}
                />
            <NewsCard
                className1='border-none group-hover:bg-button2 rounded-br-xl rounded-bl-xl  '
                className2='group-hover:bg-red rounded-br-xl rounded-bl-xl hover:text-white'
                type='NEWS'
                text='WATCH: Extended highlights of your favourite race of last year – the 2022 British Grand Prix'
                image={img}
                />
            <NewsCard
                className1='border-none group-hover:bg-button2 rounded-br-xl rounded-bl-xl  '
                className2='group-hover:bg-red rounded-br-xl rounded-bl-xl hover:text-white'
                type='NEWS'
                text='WATCH: Extended highlights of your favourite race of last year – the 2022 British Grand Prix'
                image={img}
                />
            <NewsCard
                className1='border-none group-hover:bg-button2 rounded-br-xl rounded-bl-xl  '
                className2='group-hover:bg-red rounded-br-xl rounded-bl-xl hover:text-white'
                type='NEWS'
                text='WATCH: Extended highlights of your favourite race of last year – the 2022 British Grand Prix'
                image={img}
                />

            </div>
          </div>
          <div className='bg-textgray my-5 mx-auto w-2/3 '>
            <Image src={ad} alt='ad' width={'100%'} height={'100%'} />
          </div>
        </section>

        <section>
          
          <div className='flex w-full p-4 my-2 bg-button2  '>
            <div className='flex flex-col gap-4 text-center p-2 h-[600px] w-[694px] rounded-br-xl text-white border-textgray border-r-1 border-b-1' >
                <h3>BAHRAIN</h3>
                <h2>FORMULA 1 GULF AIR BAHRAIN GRAND PRIX 2023</h2>
                <h3>03 MAR 2023 - 05 MAR 2023</h3>
                <div className=' w-full h-20 rounded-md bg-green '></div>
                <div className='absolute mr-10 w-fit float-right rounded-md py-2 px-4 border-white border-1 hover:border-2 '>
                  CONVERT TO TRACK TIME
                </div>
            </div>
          </div>      

        </section>
      </main>
    </>
  )
}
